# Entanglement Classifier Trial Notebook

### Importing Dependencies

In [1]:
import numpy as np

from components.system import System
from components.connection import ConnectionFactory
from components.model import Model
from components.connection_functions import InterfaceFunction, ReservoirFunction

### Setting up the system

In [2]:
"""
Defining System setup
"""

system_state = np.array([[1, 0], [0, 0]])

system_nodes = [0]

system_connections = {}

system = System(
    init_quantum_state=system_state, nodes=system_nodes, connections=system_connections
)

### Setting up the interface

In [3]:

"""
Defining Interface setup
"""

interfaceFactory = ConnectionFactory(InterfaceFunction, gamma_1=1, gamma_2=1)

### Setting up the reservoir

In [4]:
"""
Defining Reservoir setup
"""

reservoir_nodes=2
reservoirFactory = ConnectionFactory(ReservoirFunction, J=10)

### Setting up the model

In [5]:
model = Model()
model.setSystem(system)
model.setReservoirConnectionFac(reservoirFactory)
model.setInterfaceConectionFac(interfaceFactory)
model.generateReservoir(reservoir_nodes)
model.generateInterface()
model.setRunDuration(2.5)
model.setRunResolution(0.001)


In [6]:
model.run()

In [8]:
log = model.modelLog
log.plot()

C:\Users\mmack\anaconda3\envs\entanglement_classifier\lib\site-packages\matplotlib\cbook\__init__.py:1298: ComplexWarning: Casting complex values to real discards the imaginary part
  return np.asarray(x, float)


In [ ]:
np.linalg.eigvals(list(log.time_log.values())[1])

array([9.96005995e-01+0.j, 1.87119519e-13+0.j, 0.00000000e+00+0.j,
       0.00000000e+00+0.j, 0.00000000e+00+0.j, 0.00000000e+00+0.j,
       0.00000000e+00+0.j, 3.99400460e-03+0.j])

In [ ]:
res_nodes = model.reservoir.nodes
print(res_nodes[list(res_nodes.keys())[0]].init_quantum_state)
print(res_nodes[list(res_nodes.keys())[1]].init_quantum_state)

[[0 0]
 [0 1]]
[[0 0]
 [0 1]]
